# See full Decap documentation for further configuration: https://decapcms.org/docs/intro/
backend:
  name: git-gateway
  repo: outputwebsites/geeyourband.com # Path to the relevant GitHub repository: owner-name/repo-name
  branch: main # Branch to update, defaults to master
local_backend: true
editor:
  preview: false
media_folder: src/assets/images/media # Location where files will be stored in the repo - we store them in src so that Astro can optimize them.
public_folder: src/assets/images/media # Ensure that this path is the same as the media_folder path above.
logo_url: https://geeyourband.com/logo.svg # change url to a link to the image you want to use, no file paths, must be a URL
display_url: https://geeyourband.com
collections:
# Define the collections that will be available in the CMS. Collections Docs = https://decapcms.org/docs/collection-folder  |  Widgets Docs = https://decapcms.org/docs/widgets
- label: "Band Details" # Used in the admin dashboard UI
  name: "details" # Used in routes, e.g., /admin/collections/blog. Is also the key when fetching data from the CMS.
  files:
  - label: "Band Details" # Used in the admin dashboard UI
    name: "details" # Used in routes, e.g., /admin/collections/blog. Is also the key when fetching data from the CMS.
    file: "src/content/details/details.yml" # The path to the folder where the documents are stored
    fields:
    - { label: "Name", name: "name", widget: "string", hint: "Full name of the band." }
    - { label: "Abbreviation", name: "abbreviation", widget: "string", hint: "Short name of the band." }
    - { label: "Email", name: "email", widget: "string", hint: "Email of the band." }
    - { label: "Phone Number", name: "phone", widget: "string", hint: "Main/office telephone number of the band. Use (000) 000-0000 format." }
    - { label: "Description", name: "description", widget: "text", hint: "Short description of the band. (Max 1-2 sentences/140 characters)." }
    - { label: "Description (SEO)", name: "description_seo", widget: "text", hint: "Short description of the band. This shows in share cards. (Max 240 characters)." }
    - { label: "Website URL", name: "link_website", widget: "string", hint: "Domain name (website link/URL) of the band." }
    - { label: "Facebook URL", name: "link_facebook", widget: "string", hint: "Facebook link/URL for the band (not an individual person)." }
    - { label: "Instagram URL", name: "link_instagram", widget: "string", hint: "Instagram link/URL for the band (not an individual person)." }
    - { label: "Venmo URL", name: "link_venmo", widget: "string", hint: "Venmo link/URL for the band (not an individual person)." }
    - { label: "Band Video", name: "band_video", widget: "string", hint: "Link/URL for the official band video (reel of clips or performance recording)." }
    - { label: "Homepage Content Title", name: "homepage_title", widget: "string", hint: "Title above the homepage content." }
    - { label: "Homepage Content", name: "homepage_content", widget: "markdown", hint: "Write your homepage content in the box above." }
    - { label: "Booking Area Title", name: "book_title", widget: "string", hint: "Title above the booking area." }
    - { label: "Booking Area Content", name: "book_content", widget: "markdown", hint: "Write your booking area content in the box above." }
    - label: "Booking Bullet Points"
      name: "book_bullets"
      label_singular: "Booking Bullet Point"
      widget: "list"
      add_to_top: true
      collapsed: true
      minimize_collapsed: true
      summary: "{{fields.book_bullet}}"
      field: { label: Booking Bullet Point, name: book_bullet, widget: string, hint: "Booking Bullet Point that sells the band." }
    - { label: "Booking Sent Message", name: "book_sent", widget: "markdown", hint: "The message that appears after submitting a booking request. See at '/book-thanks'" }
    - { label: "Tip Area Title", name: "tip_title", widget: "string", hint: "Title above the tip area." }
    - { label: "Tip Area Content", name: "tip_content", widget: "markdown", hint: "Write your tip area content in the box above" }
    - { label: "Tip Message (Footer)", name: "tip_footer", widget: "markdown", hint: "The message that appears in the footer above the Venmo tip button." }
    - label: "Keywords"
      name: "keywords"
      label_singular: "Keyword"
      widget: "list"
      add_to_top: true
      collapsed: true
      minimize_collapsed: true
      summary: "{{fields.keyword}}"
      field: { label: Keyword, name: keyword, widget: string, hint: "Keyword that describes any aspect of the band which someone may use to search for the band." }
- name: "show" # Used in routes, e.g., /admin/collections/blog. Is also the key when fetching data from the CMS.
  label: "Shows" # Used in the admin dashboard UI
  label_singular: "Show" # Used in the admin dashboard UI
  description: "Shows are used to display upcoming band shows and performances. More detailed information can help attract more attendees." # Used in the admin dashboard UI
  identifier_field: title # The field that will be used to identify the document in the CMS
  folder: "src/content/show" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  fields:
  - { label: "Title", name: "title", widget: "string", hint: "Keep titles brief yet descriptive." }
  - { label: "Start Date", name: "startDate", widget: "string", hint: "Start date of the show. (ie Fri, Jun 16, 2025 | Sat, Apr 14 | Sun, Aug 9)" }
  - { label: "Start Time", name: "startTime", widget: "string", hint: "Start time of the show. (ie 7:00pm, 11:30am, 1:15am, 9:30pm)" }
  - { label: "End Date", name: "endDate", widget: "string", hint: "End date of the show. (ie Fri, Jun 16, 2025 | Sat, Apr 14 | Sun, Aug 9)" }
  - { label: "End Time", name: "endTime", widget: "string", hint: "Time the end of the show is in. (ie 7:00pm, 11:30am, 1:15am, 9:30pm)" }
  - { label: "Timezone", name: "timezone", widget: "string", required: false, hint: "Timezone the show is in. (ie EST, EDT, CST, CDT) | Default = EDT" }
  - { label: "Location Name", name: "location", widget: "string", required: false, hint: "Name of the venue the show is in. (ie The White House, Hard Rock Miami, McDonald's)" }
  - { label: "Location Address", name: "locationAddress", widget: "string", required: false, hint: "Exact address the show is located at. (ie 123 Wallaby Way, Cincinnati, OH 45213" }
  - { label: "Member", name: "member", widget: relation, collection: member, multiple: true, search_fields: [ "name" ], display_fields: [ "name" ], value_field: "{{slug}}", hint: "Select the member(s) in the show." }
  - { label: "Body", name: "body", widget: "markdown", required: false, hint: "Write your show content in the box above." }
  - { label: "Featured Image", name: "image", widget: "image", required: false, hint: "Add a photo to display at the top of the show." }
  - { label: "Featured Image Caption", name: "imageAlt", widget: "string", required: false, hint: "Add a caption to describe the featured image." }
  - { label: "Tags", name: "tags", widget: "list", required: false, hint: "Add comma-separated tags to help categorize your show. (Don't press space!)" }
- name: "member" # Used in routes, e.g., /admin/collections/blog. Is also the key when fetching data from the CMS.
  label: "Members" # Used in the admin dashboard UI
  label_singular: "Member" # Used in the admin dashboard UI
  description: "Members are used to fill out the band members section." # Used in the admin dashboard UI
  identifier_field: name # The field that will be used to identify the document in the CMS
  folder: "src/content/member" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  fields:
  - { label: "Nickname", name: "name", widget: "string", hint: "Memorable nickname for each band member." }
  - { label: "Real Name", name: "real_name", required: false, widget: "string", hint: "Enter your full name." }
  - { label: "Adjective", name: "adjective", required: false, widget: "string", hint: "Catchy and unique adjective to describe each band member." }
  - { label: "Instrument", name: "instrument", required: false, widget: "string", hint: "Instrument(s) associated with each band member." }
  - { label: "Short Bio", name: "bio", widget: "string", required: false, hint: "Add a short biography to display under your member credits." }
  - { label: "Main Member?", name: "main", widget: "boolean", hint: "True = One of the main/primary members | False = Backup or alternate member." }
  - { label: "Order", name: "order", widget: "string", hint: "Set the order of clinicians on the clinicians page. 1 = first, 2 = seconds, and so on..." }
  - { label: "Portrait BG Color", name: "photoColor", widget: "string", required: false, hint: "Set the background color behind the portrait image. (Use HEX such as #ffffff or #000000)" }
  - { label: "Portrait Image", name: "photo", widget: "image", required: false, hint: "Add a square portrait image featuring a color head shot." }
